Missing colon
It drove me crazy that the exmaple config didn't work ;)

>YAMLException: JS-YAML: missed comma between flow collection entries at line 4, column 6:
>      80 {